- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously created
      ec2:
        state: absent
        region: ap-south-1
        instance_ids: ami-0f5ee92e2d63afc18